--- @meta
--- @enum RValueType
-- Table containing all possible types of an RValue.
RValueType = {
	--- @type integer
	REAL = ...,
	--- @type integer
	STRING = ...,
	--- @type integer
	ARRAY = ...,
	--- @type integer
	PTR = ...,
	--- @type integer
	VEC3 = ...,
	--- @type integer
	UNDEFINED = ...,
	--- @type integer
	OBJECT = ...,
	--- @type integer
	INT32 = ...,
	--- @type integer
	VEC4 = ...,
	--- @type integer
	MATRIX = ...,
	--- @type integer
	INT64 = ...,
	--- @type integer
	ACCESSOR = ...,
	--- @type integer
	JSNULL = ...,
	--- @type integer
	BOOL = ...,
	--- @type integer
	ITERATOR = ...,
	--- @type integer
	REF = ...,
	--- @type integer
	UNSET = ...,
}
