--- @meta
--- @enum YYObjectBaseType
--- Table containing all possible types of an YYObjectBaseType
YYObjectBaseType = {
	--- @type integer
	YYOBJECTBASE = ...,
	--- @type integer
	----- @type integer
	CINSTANCE = ...,
	--- @type integer
	ACCESSOR = ...,
	--- @type integer
	SCRIPTREF = ...,
	--- @type integer
	PROPERTY = ...,
	--- @type integer
	ARRAY = ...,
	--- @type integer
	WEAKREF = ...,
	--- @type integer
	CONTAINER = ...,
	--- @type integer
	SEQUENCE = ...,
	--- @type integer
	SEQUENCEINSTANCE = ...,
	--- @type integer
	SEQUENCETRACK = ...,
	--- @type integer
	SEQUENCECURVE = ...,
	--- @type integer
	SEQUENCECURVECHANNEL = ...,
	--- @type integer
	SEQUENCEKEYFRAMESTORE = ...,
	--- @type integer
	SEQUENCEKEYFRAME = ...,
	--- @type integer
	SEQUENCEEVALTREE = ...,
	--- @type integer
	SEQUENCEEVALNODE = ...,
	--- @type integer
	SEQUENCEEVENT = ...,
	--- @type integer
	NINESLICE = ...,
}
