--- @meta
--- @enum ImGuiWindowFlags
ImGuiWindowFlags = {
	--- @type number
	MenuBar = ...,
	--- @type number
	NoSavedSettings = ...,
	--- @type number
	NoScrollWithMouse = ...,
	--- @type number
	NoNavInputs = ...,
	--- @type number
	Modal = ...,
	--- @type number
	NoFocusOnAppearing = ...,
	--- @type number
	Popup = ...,
	--- @type number
	NoInputs = ...,
	--- @type number
	Tooltip = ...,
	--- @type number
	NavFlattened = ...,
	--- @type number
	NoCollapse = ...,
	--- @type number
	NoDecoration = ...,
	--- @type number
	NoTitleBar = ...,
	--- @type number
	HorizontalScrollbar = ...,
	--- @type number
	ChildWindow = ...,
	--- @type number
	NoNav = ...,
	--- @type number
	None = ...,
	--- @type number
	UnsavedDocument = ...,
	--- @type number
	NoNavFocus = ...,
	--- @type number
	NoBackground = ...,
	--- @type number
	AlwaysAutoResize = ...,
	--- @type number
	NoScrollbar = ...,
	--- @type number
	ChildMenu = ...,
	--- @type number
	NoBringToFrontOnFocus = ...,
	--- @type number
	NoResize = ...,
	--- @type number
	NoMove = ...,
	--- @type number
	NoMouseInputs = ...,
	--- @type number
	AlwaysHorizontalScrollbar = ...,
	--- @type number
	AlwaysVerticalScrollbar = ...,
	--- @type number
	AlwaysUseWindowPadding = ...,
}
