--- @meta
--- @enum ImGuiStyleVar
ImGuiStyleVar = {
	--- @type integer
	IndentSpacing = ...,
	--- @type integer
	GrabRounding = ...,
	--- @type integer
	FrameBorderSize = ...,
	--- @type integer
	PopupBorderSize = ...,
	--- @type integer
	ButtonTextAlign = ...,
	--- @type integer
	WindowBorderSize = ...,
	--- @type integer
	WindowTitleAlign = ...,
	--- @type integer
	ChildRounding = ...,
	--- @type integer
	GrabMinSize = ...,
	--- @type integer
	CellPadding = ...,
	--- @type integer
	Alpha = ...,
	--- @type integer
	ItemSpacing = ...,
	--- @type integer
	SelectableTextAlign = ...,
	--- @type integer
	DisabledAlpha = ...,
	--- @type integer
	FrameRounding = ...,
	--- @type integer
	ScrollbarRounding = ...,
	--- @type integer
	ScrollbarSize = ...,
	--- @type integer
	ChildBorderSize = ...,
	--- @type integer
	TabRounding = ...,
	--- @type integer
	FramePadding = ...,
	--- @type integer
	COUNT = ...,
	--- @type integer
	WindowPadding = ...,
	--- @type integer
	PopupRounding = ...,
	--- @type integer
	WindowRounding = ...,
	--- @type integer
	ItemInnerSpacing = ...,
	--- @type integer
	WindowMinSize = ...,
}
