--- @meta
--- @enum ImGuiColorEditFlags
ImGuiColorEditFlags = {
	--- @type integer
	NoAlpha = ...,
	--- @type integer
	InputHSV = ...,
	--- @type integer
	NoDragDrop = ...,
	--- @type integer
	_InputMask = ...,
	--- @type integer
	Float = ...,
	--- @type integer
	NoOptions = ...,
	--- @type integer
	NoInputs = ...,
	--- @type integer
	NoLabel = ...,
	--- @type integer
	_PickerMask = ...,
	--- @type integer
	DisplayRGB = ...,
	--- @type integer
	_DataTypeMask = ...,
	--- @type integer
	PickerHueBar = ...,
	--- @type integer
	AlphaPreviewHalf = ...,
	--- @type integer
	_DisplayMask = ...,
	--- @type integer
	NoSidePreview = ...,
	--- @type integer
	None = ...,
	--- @type integer
	AlphaBar = ...,
	--- @type integer
	DisplayHex = ...,
	--- @type integer
	InputRGB = ...,
	--- @type integer
	PickerHueWheel = ...,
	--- @type integer
	HDR = ...,
	--- @type integer
	_OptionsDefault = ...,
	--- @type integer
	DisplayHSV = ...,
	--- @type integer
	NoSmallPreview = ...,
	--- @type integer
	Uint8 = ...,
	--- @type integer
	NoTooltip = ...,
	--- @type integer
	NoBorder = ...,
	--- @type integer
	AlphaPreview = ...,
	--- @type integer
	NoPicker = ...,
}
