--- @meta
--- @enum ImGuiCol
ImGuiCol = {
	--- @type integer
	Border = ...,
	--- @type integer
	BorderShadow = ...,
	--- @type integer
	Button = ...,
	--- @type integer
	ButtonActive = ...,
	--- @type integer
	ButtonHovered = ...,
	--- @type integer
	COUNT = ...,
	--- @type integer
	CheckMark = ...,
	--- @type integer
	ChildBg = ...,
	--- @type integer
	DragDropTarget = ...,
	--- @type integer
	FrameBg = ...,
	--- @type integer
	FrameBgActive = ...,
	--- @type integer
	FrameBgHovered = ...,
	--- @type integer
	Header = ...,
	--- @type integer
	HeaderActive = ...,
	--- @type integer
	HeaderHovered = ...,
	--- @type integer
	MenuBarBg = ...,
	--- @type integer
	ModalWindowDimBg = ...,
	--- @type integer
	NavHighlight = ...,
	--- @type integer
	NavWindowingDimBg = ...,
	--- @type integer
	NavWindowingHighlight = ...,
	--- @type integer
	PlotHistogram = ...,
	--- @type integer
	PlotHistogramHovered = ...,
	--- @type integer
	PlotLines = ...,
	--- @type integer
	PlotLinesHovered = ...,
	--- @type integer
	PopupBg = ...,
	--- @type integer
	ResizeGrip = ...,
	--- @type integer
	ResizeGripActive = ...,
	--- @type integer
	ResizeGripHovered = ...,
	--- @type integer
	ScrollbarBg = ...,
	--- @type integer
	ScrollbarGrab = ...,
	--- @type integer
	ScrollbarGrabActive = ...,
	--- @type integer
	ScrollbarGrabHovered = ...,
	--- @type integer
	Separator = ...,
	--- @type integer
	SeparatorActive = ...,
	--- @type integer
	SeparatorHovered = ...,
	--- @type integer
	SliderGrab = ...,
	--- @type integer
	SliderGrabActive = ...,
	--- @type integer
	Tab = ...,
	--- @type integer
	TabActive = ...,
	--- @type integer
	TabHovered = ...,
	--- @type integer
	TabUnfocused = ...,
	--- @type integer
	TabUnfocusedActive = ...,
	--- @type integer
	TableBorderLight = ...,
	--- @type integer
	TableBorderStrong = ...,
	--- @type integer
	TableHeaderBg = ...,
	--- @type integer
	TableRowBg = ...,
	--- @type integer
	TableRowBgAlt = ...,
	--- @type integer
	Text = ...,
	--- @type integer
	TextDisabled = ...,
	--- @type integer
	TextSelectedBg = ...,
	--- @type integer
	TitleBg = ...,
	--- @type integer
	TitleBgActive = ...,
	--- @type integer
	TitleBgCollapsed = ...,
	--- @type integer
	WindowBg = ...,
	--- @type integer
}
