--- @meta
--- @enum ImGuiKey
ImGuiKey = {
  --- @type integer
  A = ...,
  --- @type integer
  Apostrophe = ...,
  --- @type integer
  B = ...,
  --- @type integer
  Backslash = ...,
  --- @type integer
  Backspace = ...,
  --- @type integer
  C = ...,
  --- @type integer
  COUNT = ...,
  --- @type integer
  CapsLock = ...,
  --- @type integer
  Comma = ...,
  --- @type integer
  D = ...,
  --- @type integer
  Delete = ...,
  --- @type integer
  DownArrow = ...,
  --- @type integer
  E = ...,
  --- @type integer
  End = ...,
  --- @type integer
  Enter = ...,
  --- @type integer
  Equal = ...,
  --- @type integer
  Escape = ...,
  --- @type integer
  F = ...,
  --- @type integer
  F1 = ...,
  --- @type integer
  F10 = ...,
  --- @type integer
  F11 = ...,
  --- @type integer
  F12 = ...,
  --- @type integer
  F2 = ...,
  --- @type integer
  F3 = ...,
  --- @type integer
  F4 = ...,
  --- @type integer
  F5 = ...,
  --- @type integer
  F6 = ...,
  --- @type integer
  F7 = ...,
  --- @type integer
  F8 = ...,
  --- @type integer
  F9 = ...,
  --- @type integer
  G = ...,
  --- @type integer
  GamepadBack = ...,
  --- @type integer
  GamepadDpadDown = ...,
  --- @type integer
  GamepadDpadLeft = ...,
  --- @type integer
  GamepadDpadRight = ...,
  --- @type integer
  GamepadDpadUp = ...,
  --- @type integer
  GamepadFaceDown = ...,
  --- @type integer
  GamepadFaceLeft = ...,
  --- @type integer
  GamepadFaceRight = ...,
  --- @type integer
  GamepadFaceUp = ...,
  --- @type integer
  GamepadL1 = ...,
  --- @type integer
  GamepadL2 = ...,
  --- @type integer
  GamepadL3 = ...,
  --- @type integer
  GamepadLStickDown = ...,
  --- @type integer
  GamepadLStickLeft = ...,
  --- @type integer
  GamepadLStickRight = ...,
  --- @type integer
  GamepadLStickUp = ...,
  --- @type integer
  GamepadR1 = ...,
  --- @type integer
  GamepadR2 = ...,
  --- @type integer
  GamepadR3 = ...,
  --- @type integer
  GamepadRStickDown = ...,
  --- @type integer
  GamepadRStickLeft = ...,
  --- @type integer
  GamepadRStickRight = ...,
  --- @type integer
  GamepadRStickUp = ...,
  --- @type integer
  GamepadStart = ...,
  --- @type integer
  GraveAccent = ...,
  --- @type integer
  H = ...,
  --- @type integer
  Home = ...,
  --- @type integer
  I = ...,
  --- @type integer
  Insert = ...,
  --- @type integer
  J = ...,
  --- @type integer
  K = ...,
  --- @type integer
  Keypad0 = ...,
  --- @type integer
  Keypad1 = ...,
  --- @type integer
  Keypad2 = ...,
  --- @type integer
  Keypad3 = ...,
  --- @type integer
  Keypad4 = ...,
  --- @type integer
  Keypad5 = ...,
  --- @type integer
  Keypad6 = ...,
  --- @type integer
  Keypad7 = ...,
  --- @type integer
  Keypad8 = ...,
  --- @type integer
  Keypad9 = ...,
  --- @type integer
  KeypadAdd = ...,
  --- @type integer
  KeypadDecimal = ...,
  --- @type integer
  KeypadDivide = ...,
  --- @type integer
  KeypadEnter = ...,
  --- @type integer
  KeypadEqual = ...,
  --- @type integer
  KeypadMultiply = ...,
  --- @type integer
  KeypadSubtract = ...,
  --- @type integer
  L = ...,
  --- @type integer
  LeftAlt = ...,
  --- @type integer
  LeftArrow = ...,
  --- @type integer
  LeftBracket = ...,
  --- @type integer
  LeftCtrl = ...,
  --- @type integer
  LeftShift = ...,
  --- @type integer
  LeftSuper = ...,
  --- @type integer
  M = ...,
  --- @type integer
  Menu = ...,
  --- @type integer
  Minus = ...,
  --- @type integer
  MouseLeft = ...,
  --- @type integer
  MouseMiddle = ...,
  --- @type integer
  MouseRight = ...,
  --- @type integer
  MouseWheelX = ...,
  --- @type integer
  MouseWheelY = ...,
  --- @type integer
  MouseX1 = ...,
  --- @type integer
  MouseX2 = ...,
  --- @type integer
  N = ...,
  --- @type integer
  None = ...,
  --- @type integer
  NumLock = ...,
  --- @type integer
  O = ...,
  --- @type integer
  P = ...,
  --- @type integer
  PageDown = ...,
  --- @type integer
  PageUp = ...,
  --- @type integer
  Pause = ...,
  --- @type integer
  Period = ...,
  --- @type integer
  PrintScreen = ...,
  --- @type integer
  Q = ...,
  --- @type integer
  R = ...,
  --- @type integer
  RightAlt = ...,
  --- @type integer
  RightArrow = ...,
  --- @type integer
  RightBracket = ...,
  --- @type integer
  RightCtrl = ...,
  --- @type integer
  RightShift = ...,
  --- @type integer
  RightSuper = ...,
  --- @type integer
  S = ...,
  --- @type integer
  ScrollLock = ...,
  --- @type integer
  Semicolon = ...,
  --- @type integer
  Slash = ...,
  --- @type integer
  Space = ...,
  --- @type integer
  T = ...,
  --- @type integer
  Tab = ...,
  --- @type integer
  U = ...,
  --- @type integer
  UpArrow = ...,
  --- @type integer
  V = ...,
  --- @type integer
  W = ...,
  --- @type integer
  X = ...,
  --- @type integer
  Y = ...,
  --- @type integer
  Z = ...,
  --- @type integer
  _0 = ...,
  --- @type integer
  _1 = ...,
  --- @type integer
  _2 = ...,
  --- @type integer
  _3 = ...,
  --- @type integer
  _4 = ...,
  --- @type integer
  _5 = ...,
  --- @type integer
  _6 = ...,
  --- @type integer
  _7 = ...,
  --- @type integer
  _8 = ...,
  --- @type integer
  _9 = ...,
  --- @type integer
}
