--- @meta
--- @enum ImGuiTableFlags
ImGuiTableFlags = {
	--- @type integer
	NoSavedSettings = ...,
	--- @type integer
	SizingFixedFit = ...,
	--- @type integer
	NoKeepColumnsVisible = ...,
	--- @type integer
	ScrollX = ...,
	--- @type integer
	NoPadInnerX = ...,
	--- @type integer
	SortTristate = ...,
	--- @type integer
	NoPadOuterX = ...,
	--- @type integer
	BordersV = ...,
	--- @type integer
	SizingMask = ...,
	--- @type integer
	Reorderable = ...,
	--- @type integer
	SizingStretchProp = ...,
	--- @type integer
	BordersH = ...,
	--- @type integer
	NoHostExtendX = ...,
	--- @type integer
	Borders = ...,
	--- @type integer
	BordersInnerV = ...,
	--- @type integer
	ContextMenuInBody = ...,
	--- @type integer
	SortMulti = ...,
	--- @type integer
	NoClip = ...,
	--- @type integer
	RowBg = ...,
	--- @type integer
	BordersInner = ...,
	--- @type integer
	ScrollY = ...,
	--- @type integer
	NoHostExtendY = ...,
	--- @type integer
	None = ...,
	--- @type integer
	PadOuterX = ...,
	--- @type integer
	PreciseWidths = ...,
	--- @type integer
	Resizable = ...,
	--- @type integer
	SizingFixedSame = ...,
	--- @type integer
	Sortable = ...,
	--- @type integer
	SizingStretchSame = ...,
	--- @type integer
	BordersOuter = ...,
	--- @type integer
	Hideable = ...,
	--- @type integer
	NoBordersInBody = ...,
	--- @type integer
	NoBordersInBodyUntilResize = ...,
	--- @type integer
	BordersOuterV = ...,
	--- @type integer
	BordersOuterH = ...,
	--- @type integer
	BordersInnerH = ...,
	--- @type integer
}
