--- @meta
--- @enum ImGuiTableColumnFlags
ImGuiTableColumnFlags = {
	--- @type integer
	DefaultHide = ...,
	--- @type integer
	DefaultSort = ...,
	--- @type integer
	Disabled = ...,
	--- @type integer
	IndentDisable = ...,
	--- @type integer
	IndentEnable = ...,
	--- @type integer
	IndentMask_ = ...,
	--- @type integer
	IsEnabled = ...,
	--- @type integer
	IsHovered = ...,
	--- @type integer
	IsSorted = ...,
	--- @type integer
	IsVisible = ...,
	--- @type integer
	NoClip = ...,
	--- @type integer
	NoDirectResize_ = ...,
	--- @type integer
	NoHeaderLabel = ...,
	--- @type integer
	NoHeaderWidth = ...,
	--- @type integer
	NoHide = ...,
	--- @type integer
	NoReorder = ...,
	--- @type integer
	NoResize = ...,
	--- @type integer
	NoSort = ...,
	--- @type integer
	NoSortAscending = ...,
	--- @type integer
	NoSortDescending = ...,
	--- @type integer
	None = ...,
	--- @type integer
	PreferSortAscending = ...,
	--- @type integer
	PreferSortDescending = ...,
	--- @type integer
	StatusMask_ = ...,
	--- @type integer
	WidthFixed = ...,
	--- @type integer
	WidthMask_ = ...,
	--- @type integer
	WidthStretch = ...,
}
